### ISSUE TITLE
Error running yarn run build-ts

### ISSUE THREAD

**Issue by adklempner** [XLNT/gnarly#6]
```
yarn run v1.3.2
$ lerna exec --parallel -- yarn run build-ts
lerna info version 2.11.0
lerna info exec in 5 package(s): yarn run build-ts
@xlnt/gnarly-bin: $ tsc
@xlnt/gnarly-reducer-erc721: $ tsc
@xlnt/gnarly-reducer-events: $ tsc
@xlnt/gnarly-core: $ tsc
@xlnt/gnarly-reducer-block-meta: $ tsc
@xlnt/gnarly-core: src/Ourbit.ts(10,8): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
@xlnt/gnarly-core: src/utils.ts(1,27): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
@xlnt/gnarly-core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@xlnt/gnarly-core: error Command failed with exit code 2.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build-ts
lerna ERR! error Command failed with exit code 2.
lerna ERR! 
lerna ERR! $ tsc
lerna ERR! src/Ourbit.ts(10,8): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
lerna ERR! src/utils.ts(1,27): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/aklempner/Repos/ETHBA/gnarly/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: yarn run build-ts
error Command failed with exit code 2.

$ tsc
src/Ourbit.ts(10,8): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
src/utils.ts(1,27): error TS2307: Cannot find module '@xlnt/fast-json-patch'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/aklempner/Repos/ETHBA/gnarly/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '$ tsc\nsrc/Ourbit.ts(10,8): error TS2307: Cannot find module \'@xlnt/fast-json-patch\'.\nsrc/utils.ts(1,27): error TS2307: Cannot find module \'@xlnt/fast-json-patch\'.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build-ts',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by shrugs** [comment]
Actually, I'm getting this same issue on a fresh clone and attempting to set up the project. Fixing now

**Comment by shrugs** [comment]
cool, fixed it; let me know if it looks good on your end. README instructions should be 👍

**Comment by kolya182** [comment]
@shrugs I'm getting this issue
```js
Mykolas-MacBook-Pro:gnarly mykola$ yarn run build-ts
yarn run v1.7.0
$ lerna exec --parallel -- yarn run build-ts
lerna info version 2.11.0
lerna info exec in 5 package(s): yarn run build-ts
@xlnt/gnarly-bin: $ tsc
@xlnt/gnarly-reducer-events: $ tsc
@xlnt/gnarly-core: $ tsc
@xlnt/gnarly-reducer-erc721: $ tsc
@xlnt/gnarly-reducer-block-meta: $ tsc
@xlnt/gnarly-reducer-events: src/models/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-events: src/reducer.ts(14,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-events: src/stores/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-block-meta: src/models/sequelize.ts(3,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-block-meta: src/reducer.ts(9,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-block-meta: src/stores/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-events: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@xlnt/gnarly-bin: src/index.ts(21,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-bin: src/index.ts(25,8): error TS2307: Cannot find module '@xlnt/gnarly-reducer-erc721'.
@xlnt/gnarly-bin: src/index.ts(29,8): error TS2307: Cannot find module '@xlnt/gnarly-reducer-block-meta'.
@xlnt/gnarly-bin: src/index.ts(33,8): error TS2307: Cannot find module '@xlnt/gnarly-reducer-events'.
@xlnt/gnarly-reducer-events: error Command failed with exit code 2.
@xlnt/gnarly-reducer-erc721: src/models/sequelize.ts(3,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-erc721: src/reducer.ts(15,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
@xlnt/gnarly-reducer-erc721: src/stores/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build-ts
lerna ERR! error Command failed with exit code 2.
lerna ERR!
lerna ERR! $ tsc
lerna ERR! src/models/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
lerna ERR! src/reducer.ts(14,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
lerna ERR! src/stores/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/mykola/git/gnarly/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
@xlnt/gnarly-reducer-block-meta: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@xlnt/gnarly-bin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@xlnt/gnarly-reducer-block-meta: error Command failed with exit code 2.
@xlnt/gnarly-reducer-erc721: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@xlnt/gnarly-bin: error Command failed with exit code 2.
@xlnt/gnarly-reducer-erc721: error Command failed with exit code 2.
{ Error: Command failed: yarn run build-ts
error Command failed with exit code 2.

$ tsc
src/models/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
src/reducer.ts(14,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
src/stores/sequelize.ts(5,8): error TS2307: Cannot find module '@xlnt/gnarly-core'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/mykola/git/gnarly/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: '$ tsc\nsrc/models/sequelize.ts(5,8): error TS2307: Cannot find module \'@xlnt/gnarly-core\'.\nsrc/reducer.ts(14,8): error TS2307: Cannot find module \'@xlnt/gnarly-core\'.\nsrc/stores/sequelize.ts(5,8): error TS2307: Cannot find module \'@xlnt/gnarly-core\'.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build-ts',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Mykolas-MacBook-Pro:gnarly mykola$
```
